// SPDX-License-Identifier: MIT
pragma solidity <0.9.0 >=0.8.19;

// NOTE: DO NOT EDIT this file!
// This file is generated from https://github.com/get-smooth/crypto-lib, using
// `forge flatten ./src/lib/libSCL_EIP6565.sol | sed 's|///|//|g' > eip6565.sol`
// on commit d714e9824e2e2e44be3c8fd498e0de651ddc9425.
//
// Also added wrapper:
// function verifyLEWithPubkey(string memory m, uint256 r, uint256 s, bytes32 pubkey, uint256 qx, uint256 qy)


// external/sha512/LibBytes.sol

/*

  Copyright 2018 ZeroEx Intl.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

*/

// solhint-disable max-line-length
// Original library copied from
// https://github.com/0xProject/exchange-v3/blob/aae46bef841bfd1cc31028f41793db4fe7197084/contracts/utils/contracts/src/LibBytes.sol
// solhint-enable max-line-length

library LibBytes {
    using LibBytes for bytes;

    // @dev Gets the memory address for a byte array.
    // @param input Byte array to lookup.
    // @return memoryAddress Memory address of byte array. This
    //         points to the header of the byte array which contains
    //         the length.
    function rawAddress(bytes memory input) internal pure returns (uint256 memoryAddress) {
        assembly {
            memoryAddress := input
        }
        return memoryAddress;
    }

    // @dev Gets the memory address for the contents of a byte array.
    // @param input Byte array to lookup.
    // @return memoryAddress Memory address of the contents of the byte array.
    function contentAddress(bytes memory input) internal pure returns (uint256 memoryAddress) {
        assembly {
            memoryAddress := add(input, 32)
        }
        return memoryAddress;
    }

    // @dev Copies `length` bytes from memory location `source` to `dest`.
    // @param dest memory address to copy bytes to.
    // @param source memory address to copy bytes from.
    // @param length number of bytes to copy.
    function memCopy(uint256 dest, uint256 source, uint256 length) internal pure {
        if (length < 32) {
            // Handle a partial word by reading destination and masking
            // off the bits we are interested in.
            // This correctly handles overlap, zero lengths and source == dest
            assembly {
                let mask := sub(exp(256, sub(32, length)), 1)
                let s := and(mload(source), not(mask))
                let d := and(mload(dest), mask)
                mstore(dest, or(s, d))
            }
        } else {
            // Skip the O(length) loop when source == dest.
            if (source == dest) {
                return;
            }

            // For large copies we copy whole words at a time. The final
            // word is aligned to the end of the range (instead of after the
            // previous) to handle partial words. So a copy will look like this:
            //
            //  ####
            //      ####
            //          ####
            //            ####
            //
            // We handle overlap in the source and destination range by
            // changing the copying direction. This prevents us from
            // overwriting parts of source that we still need to copy.
            //
            // This correctly handles source == dest
            //
            if (source > dest) {
                assembly {
                    // We subtract 32 from `sEnd` and `dEnd` because it
                    // is easier to compare with in the loop, and these
                    // are also the addresses we need for copying the
                    // last bytes.
                    length := sub(length, 32)
                    let sEnd := add(source, length)
                    let dEnd := add(dest, length)

                    // Remember the last 32 bytes of source
                    // This needs to be done here and not after the loop
                    // because we may have overwritten the last bytes in
                    // source already due to overlap.
                    let last := mload(sEnd)

                    // Copy whole words front to back
                    // Note: the first check is always true,
                    // this could have been a do-while loop.
                    // solhint-disable-next-line no-empty-blocks
                    for {

                    } lt(source, sEnd) {

                    } {
                        mstore(dest, mload(source))
                        source := add(source, 32)
                        dest := add(dest, 32)
                    }

                    // Write the last 32 bytes
                    mstore(dEnd, last)
                }
            } else {
                assembly {
                    // We subtract 32 from `sEnd` and `dEnd` because those
                    // are the starting points when copying a word at the end.
                    length := sub(length, 32)
                    let sEnd := add(source, length)
                    let dEnd := add(dest, length)

                    // Remember the first 32 bytes of source
                    // This needs to be done here and not after the loop
                    // because we may have overwritten the first bytes in
                    // source already due to overlap.
                    let first := mload(source)

                    // Copy whole words back to front
                    // We use a signed comparisson here to allow dEnd to become
                    // negative (happens when source and dest < 32). Valid
                    // addresses in local memory will never be larger than
                    // 2**255, so they can be safely re-interpreted as signed.
                    // Note: the first check is always true,
                    // this could have been a do-while loop.
                    // solhint-disable-next-line no-empty-blocks
                    for {

                    } slt(dest, dEnd) {

                    } {
                        mstore(dEnd, mload(sEnd))
                        sEnd := sub(sEnd, 32)
                        dEnd := sub(dEnd, 32)
                    }

                    // Write the first 32 bytes
                    mstore(dest, first)
                }
            }
        }
    }

    // @dev Returns a slices from a byte array.
    // @param b The byte array to take a slice from.
    // @param from The starting index for the slice (inclusive).
    // @param to The final index for the slice (exclusive).
    // @return result The slice containing bytes at indices [from, to)
    function slice(bytes memory b, uint256 from, uint256 to) internal pure returns (bytes memory result) {
        require(from <= to, "FROM_LESS_THAN_TO_REQUIRED");
        require(to <= b.length, "TO_LESS_THAN_LENGTH_REQUIRED");

        // Create a new bytes structure and copy contents
        result = new bytes(to - from);
        memCopy(result.contentAddress(), b.contentAddress() + from, result.length);
        return result;
    }

    // @dev Returns a slice from a byte array without preserving the input.
    // @param b The byte array to take a slice from. Will be destroyed in the process.
    // @param from The starting index for the slice (inclusive).
    // @param to The final index for the slice (exclusive).
    // @return result The slice containing bytes at indices [from, to)
    // @dev When `from == 0`, the original array will match the slice. In other cases its state will be corrupted.
    function sliceDestructive(bytes memory b, uint256 from, uint256 to) internal pure returns (bytes memory result) {
        require(from <= to, "FROM_LESS_THAN_TO_REQUIRED");
        require(to <= b.length, "TO_LESS_THAN_LENGTH_REQUIRED");

        // Create a new bytes structure around [from, to) in-place.
        assembly {
            result := add(b, from)
            mstore(result, sub(to, from))
        }
        return result;
    }

    // @dev Pops the last byte off of a byte array by modifying its length.
    // @param b Byte array that will be modified.
    // @return result The byte that was popped off.
    function popLastByte(bytes memory b) internal pure returns (bytes1 result) {
        require(b.length > 0, "GREATER_THAN_ZERO_LENGTH_REQUIRED");

        // Store last byte.
        result = b[b.length - 1];

        assembly {
            // Decrement length of byte array.
            let newLen := sub(mload(b), 1)
            mstore(b, newLen)
        }
        return result;
    }

    // @dev Pops the last 20 bytes off of a byte array by modifying its length.
    // @param b Byte array that will be modified.
    // @return result The 20 byte address that was popped off.
    function popLast20Bytes(bytes memory b) internal pure returns (address result) {
        require(b.length >= 20, "GREATER_OR_EQUAL_TO_20_LENGTH_REQUIRED");

        // Store last 20 bytes.
        result = readAddress(b, b.length - 20);

        assembly {
            // Subtract 20 from byte array length.
            let newLen := sub(mload(b), 20)
            mstore(b, newLen)
        }
        return result;
    }

    // @dev Tests equality of two byte arrays.
    // @param lhs First byte array to compare.
    // @param rhs Second byte array to compare.
    // @return equal True if arrays are the same. False otherwise.
    function equals(bytes memory lhs, bytes memory rhs) internal pure returns (bool equal) {
        // Keccak gas cost is 30 + numWords * 6. This is a cheap way to compare.
        // We early exit on unequal lengths, but keccak would also correctly
        // handle this.
        return lhs.length == rhs.length && keccak256(lhs) == keccak256(rhs);
    }

    // @dev Reads an address from a position in a byte array.
    // @param b Byte array containing an address.
    // @param index Index in byte array of address.
    // @return result address from byte array.
    function readAddress(bytes memory b, uint256 index) internal pure returns (address result) {
        require(
            b.length >= index + 20, // 20 is length of address
            "GREATER_OR_EQUAL_TO_20_LENGTH_REQUIRED"
        );

        // Add offset to index:
        // 1. Arrays are prefixed by 32-byte length parameter (add 32 to index)
        // 2. Account for size difference between address length and 32-byte storage word (subtract 12 from index)
        index += 20;

        // Read address from array memory
        assembly {
            // 1. Add index to address of bytes array
            // 2. Load 32-byte word from memory
            // 3. Apply 20-byte mask to obtain address
            result := and(mload(add(b, index)), 0xffffffffffffffffffffffffffffffffffffffff)
        }
        return result;
    }

    // @dev Writes an address into a specific position in a byte array.
    // @param b Byte array to insert address into.
    // @param index Index in byte array of address.
    // @param input Address to put into byte array.
    function writeAddress(bytes memory b, uint256 index, address input) internal pure {
        require(
            b.length >= index + 20, // 20 is length of address
            "GREATER_OR_EQUAL_TO_20_LENGTH_REQUIRED"
        );

        // Add offset to index:
        // 1. Arrays are prefixed by 32-byte length parameter (add 32 to index)
        // 2. Account for size difference between address length and 32-byte storage word (subtract 12 from index)
        index += 20;

        // Store address into array memory
        assembly {
            // The address occupies 20 bytes and mstore stores 32 bytes.
            // First fetch the 32-byte word where we'll be storing the address, then
            // apply a mask so we have only the bytes in the word that the address will not occupy.
            // Then combine these bytes with the address and store the 32 bytes back to memory with mstore.

            // 1. Add index to address of bytes array
            // 2. Load 32-byte word from memory
            // 3. Apply 12-byte mask to obtain extra bytes occupying word of memory where we'll store the address
            let neighbors := and(
                mload(add(b, index)),
                0xffffffffffffffffffffffff0000000000000000000000000000000000000000
            )

            // Make sure input address is clean.
            // (Solidity does not guarantee this)
            input := and(input, 0xffffffffffffffffffffffffffffffffffffffff)

            // Store the neighbors and address into memory
            mstore(add(b, index), xor(input, neighbors))
        }
    }

    // @dev Reads a bytes32 value from a position in a byte array.
    // @param b Byte array containing a bytes32 value.
    // @param index Index in byte array of bytes32 value.
    // @return result bytes32 value from byte array.
    function readBytes32(bytes memory b, uint256 index) internal pure returns (bytes32 result) {
        require(b.length >= index + 32, "GREATER_OR_EQUAL_TO_32_LENGTH_REQUIRED");

        // Arrays are prefixed by a 256 bit length parameter
        index += 32;

        // Read the bytes32 from array memory
        assembly {
            result := mload(add(b, index))
        }
        return result;
    }

    // @dev Writes a bytes32 into a specific position in a byte array.
    // @param b Byte array to insert <input> into.
    // @param index Index in byte array of <input>.
    // @param input bytes32 to put into byte array.
    function writeBytes32(bytes memory b, uint256 index, bytes32 input) internal pure {
        require(b.length >= index + 32, "GREATER_OR_EQUAL_TO_32_LENGTH_REQUIRED");

        // Arrays are prefixed by a 256 bit length parameter
        index += 32;

        // Read the bytes32 from array memory
        assembly {
            mstore(add(b, index), input)
        }
    }

    // @dev Reads a uint256 value from a position in a byte array.
    // @param b Byte array containing a uint256 value.
    // @param index Index in byte array of uint256 value.
    // @return result uint256 value from byte array.
    function readUint256(bytes memory b, uint256 index) internal pure returns (uint256 result) {
        result = uint256(readBytes32(b, index));
        return result;
    }

    // @dev Writes a uint256 into a specific position in a byte array.
    // @param b Byte array to insert <input> into.
    // @param index Index in byte array of <input>.
    // @param input uint256 to put into byte array.
    function writeUint256(bytes memory b, uint256 index, uint256 input) internal pure {
        writeBytes32(b, index, bytes32(input));
    }

    // @dev Reads an unpadded bytes4 value from a position in a byte array.
    // @param b Byte array containing a bytes4 value.
    // @param index Index in byte array of bytes4 value.
    // @return result bytes4 value from byte array.
    function readBytes4(bytes memory b, uint256 index) internal pure returns (bytes4 result) {
        require(b.length >= index + 4, "GREATER_OR_EQUAL_TO_4_LENGTH_REQUIRED");

        // Arrays are prefixed by a 32 byte length field
        index += 32;

        // Read the bytes4 from array memory
        assembly {
            result := mload(add(b, index))
            // Solidity does not require us to clean the trailing bytes.
            // We do it anyway
            result := and(result, 0xFFFFFFFF00000000000000000000000000000000000000000000000000000000)
        }
        return result;
    }

    // @dev Reads an unpadded bytes8 value from a position in a byte array.
    // @param b Byte array containing a bytes8 value.
    // @param index Index in byte array of bytes4 value.
    // @return result bytes8 value from byte array.
    function readBytes8(bytes memory b, uint256 index) internal pure returns (bytes8 result) {
        require(b.length >= index + 8, "GREATER_OR_EQUAL_TO_8_LENGTH_REQUIRED");

        // Arrays are prefixed by a 32 byte length field
        index += 32;

        // Read the bytes8 from array memory
        assembly {
            result := mload(add(b, index))
            // Solidity does not require us to clean the trailing bytes.
            // We do it anyway
            result := and(result, 0xFFFFFFFFFFFFFFFF000000000000000000000000000000000000000000000000)
        }
        return result;
    }

    // @dev Reads an unpadded bytes2 value from a position in a byte array.
    // @param b Byte array containing a bytes2 value.
    // @param index Index in byte array of bytes2 value.
    // @return result bytes2 value from byte array.
    function readBytes2(bytes memory b, uint256 index) internal pure returns (bytes2 result) {
        require(b.length >= index + 2, "GREATER_OR_EQUAL_TO_2_LENGTH_REQUIRED");

        // Arrays are prefixed by a 32 byte length field
        index += 32;

        // Read the bytes2 from array memory
        assembly {
            result := mload(add(b, index))
            // Solidity does not require us to clean the trailing bytes.
            // We do it anyway
            result := and(result, 0xFFFF000000000000000000000000000000000000000000000000000000000000)
        }
        return result;
    }

    // @dev Reads nested bytes from a specific position.
    // @dev NOTE: the returned value overlaps with the input value.
    //            Both should be treated as immutable.
    // @param b Byte array containing nested bytes.
    // @param index Index of nested bytes.
    // @return result Nested bytes.
    function readBytesWithLength(bytes memory b, uint256 index) internal pure returns (bytes memory result) {
        // Read length of nested bytes
        uint256 nestedBytesLength = readUint256(b, index);
        index += 32;

        // Assert length of <b> is valid, given
        // length of nested bytes
        require(b.length >= index + nestedBytesLength, "GREATER_OR_EQUAL_TO_NESTED_BYTES_LENGTH_REQUIRED");

        // Return a pointer to the byte array as it exists inside `b`
        assembly {
            result := add(b, index)
        }
        return result;
    }

    // @dev Inserts bytes at a specific position in a byte array.
    // @param b Byte array to insert <input> into.
    // @param index Index in byte array of <input>.
    // @param input bytes to insert.
    function writeBytesWithLength(bytes memory b, uint256 index, bytes memory input) internal pure {
        // Assert length of <b> is valid, given
        // length of input
        require(
            b.length >= index + 32 + input.length, // 32 bytes to store length
            "GREATER_OR_EQUAL_TO_NESTED_BYTES_LENGTH_REQUIRED"
        );

        // Copy <input> into <b>
        memCopy(
            b.contentAddress() + index,
            input.rawAddress(), // includes length of <input>
            input.length + 32 // +32 bytes to store <input> length
        );
    }

    // @dev Performs a deep copy of a byte array onto another byte array of greater than or equal length.
    // @param dest Byte array that will be overwritten with source bytes.
    // @param source Byte array to copy onto dest bytes.
    function deepCopyBytes(bytes memory dest, bytes memory source) internal pure {
        uint256 sourceLen = source.length;
        // Dest length must be >= source length, or some bytes would not be copied.
        require(dest.length >= sourceLen, "GREATER_OR_EQUAL_TO_SOURCE_BYTES_LENGTH_REQUIRED");
        memCopy(dest.contentAddress(), source.contentAddress(), sourceLen);
    }
}

// src/elliptic/SCL_ecOncurve.sol
/********************************************************************************************/
/*
/*   ╔═╗╔╦╗╔═╗╔═╗╔╦╗╦ ╦  ╔═╗╦═╗╦ ╦╔═╗╔╦╗╔═╗╦  ╦╔╗ 
/*   ╚═╗║║║║ ║║ ║ ║ ╠═╣  ║  ╠╦╝╚╦╝╠═╝ ║ ║ ║║  ║╠╩╗
/*   ╚═╝╩ ╩╚═╝╚═╝o╩ ╩ ╩  ╚═╝╩╚═ ╩ ╩   ╩ ╚═╝╩═╝╩╚═╝
/*              
/* Copyright (C) 2024 - Renaud Dubois - This file is part of SCL (Smoo.th CryptoLib) project
/* License: This software is licensed under MIT License (and allways will)  
/* Description : testing the validity of an input point                                      
/********************************************************************************************/

    // @notice Check the validity of a Public keys
    // @param qx The x value of the public key Q used for the signature
    // @param qy The y value of the public key Q used for the signature
    // @dev Note The public key is assumed to belong to the curve and not neutral, additional weak keys are rejected 

function ec_isOnCurve(uint256 p, uint256 a, uint256 b, uint256 qx, uint256 qy) 
pure returns (bool)
{
  // check the validity of the range related to prime field characteristic
         if ( (qx == 0 && qy == 0) || qx >= p  || qy >= p) {
            return false;
        }
 // check the curve equation
        uint256 LHS = mulmod(qy, qy, p); // y^2
        uint256 RHS = addmod(mulmod(mulmod(qx, qx, p), qx, p), mulmod(qx, a, p), p); // x^3+ax
        RHS = addmod(RHS, b, p); // x^3 + a*x + b

        return LHS == RHS;
}

// src/include/SCL_errcodes.sol
/********************************************************************************************/
/*
/*   ╔═╗╔╦╗╔═╗╔═╗╔╦╗╦ ╦  ╔═╗╦═╗╦ ╦╔═╗╔╦╗╔═╗╦  ╦╔╗ 
/*   ╚═╗║║║║ ║║ ║ ║ ╠═╣  ║  ╠╦╝╚╦╝╠═╝ ║ ║ ║║  ║╠╩╗
/*   ╚═╝╩ ╩╚═╝╚═╝o╩ ╩ ╩  ╚═╝╩╚═ ╩ ╩   ╩ ╚═╝╩═╝╩╚═╝
/*              
/* Copyright (C) 2024 - Renaud Dubois - This file is part of SCL (Smoo.th CryptoLib) project
/* License: This software is licensed under MIT License (and allways will)  
/* Description : testing the validity of an input point                                      
/********************************************************************************************/

//error calling modInv
uint256 constant _ModInvError=0x7FE;
//error calling modExpPrecompile
uint256 constant _ModExpError=0x7FF;

//error due to calling square root computation on non residue number
uint256 constant _NotQuadraticResidueError=0x7FC;

// src/include/SCL_mask.h.sol
//********************************************************************************************/
//*
//*     ___                _   _       ___               _         _    _ _    
//*    / __|_ __  ___  ___| |_| |_    / __|_ _ _  _ _ __| |_ ___  | |  (_) |__ 
//*    \__ \ '  \/ _ \/ _ \  _| ' \  | (__| '_| || | '_ \  _/ _ \ | |__| | '_ \
//*   |___/_|_|_\___/\___/\__|_||_|  \___|_|  \_, | .__/\__\___/ |____|_|_.__/
//*                                         |__/|_|           
//*              
//* Copyright (C) 2023 - Renaud Dubois - This file is part of SCL (Smooth CryptoLib) project
//* License: This software is licensed under MIT License                                        
//********************************************************************************************/

// prime field modulus of the ed25519 curve
uint256 constant _MASK128 = 0xffffffffffffffffffffffffffffffff;
uint256 constant _HI_SCALAR=128;
uint256 constant _HIBIT_CURVE_0=255;

// prime field modulus of the secp256r1 curve
uint256 constant MODEXP_PRECOMPILE=0x05;

/* curves are identified by their OID */
uint256 constant _SECP256R1=0x06082A648CE3D030107;
uint256 constant _ED25519=  0x060a2b060104019755010501;
uint256 constant _SECP256K1=0x06052B8104000A;
uint256 constant _STARKCURVE=0x01;//OID doesn't exist for stark curve
uint256 constant _BABYJJ=0x02;
uint256 constant _ZERO_U256=0x0000000000000000000000000000000000000000000000000000000000000000;

uint256 constant _UNUSED=0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1;
//when a constant shall be defined
uint256 constant _TODO=0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff3;

// src/fields/SCL_wei25519.sol
/********************************************************************************************/
/*
/*     ___                _   _       ___               _         _    _ _    
/*    / __|_ __  ___  ___| |_| |_    / __|_ _ _  _ _ __| |_ ___  | |  (_) |__ 
/*    \__ \ '  \/ _ \/ _ \  _| ' \  | (__| '_| || | '_ \  _/ _ \ | |__| | '_ \
/*   |___/_|_|_\___/\___/\__|_||_|  \___|_|  \_, | .__/\__\___/ |____|_|_.__/
/*                                         |__/|_|           
/*              
/* Copyright (C) 2023 - Renaud Dubois - This file is part of SCL (Smooth CryptoLib) project
/* License: This software is licensed under MIT License                                        
/********************************************************************************************/

// prime field modulus of the ed25519 curve
uint256 constant p_0 = 0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffed;
// -2 mod(p), used to accelerate inversion and doubling operations by avoiding negation
// the representation of -1 in this field
uint256 constant pMINUS_1 = 0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec;
uint256 constant pMINUS_2_0 = 0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeb;

// short weierstrass first coefficient 
uint256 constant a_0 = 19298681539552699237261830834781317975544997444273427339909597334573241639236;
// short weierstrass second coefficient 0x41a3b6bfc668778ebe2954a4b1df36d1485ecef1ea614295796e102240891faa
uint256 constant b_0 =55751746669818908907645289078257140818241103727901012315294400837956729358436;
uint256 constant n_0 = 0x1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3ed;
//2^256 mod n used for big integer reduction modulo n
uint256 constant _2pow256modn = 0xffffffffffffffffffffffffffffffec6ef5bf4737dcf70d6ec31748d98951d;

uint256 constant nMINUS_2_0 = 0x1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3eb;

uint256 constant gx_0=0x2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad245a;
uint256 constant gy_0=0x20ae19a1b8a086b4e01edd2c7748d14c923d4d7e6d7c61b229e9c5a27eced3d9;
//Computed with sage:
//wei25519_gx2pow128=12508890695284219941432954705462464418216687521194464129735840385450754660239;
//wei25519_gy2pow128=38799853089443519372474884917849014410429794312182895329810583938938235910009;
//0x1ba7c7ff0d602e0108a3dd49027e624914307ae10b22d566e567558e115f578f
uint256 constant gpow2p128_x_0 =12508890695284219941432954705462464418216687521194464129735840385450754660239;
//0x55c7f0494056ac055fdb19191577ef9b2055b5b165e04291aaf7187e6519f779
uint256 constant gpow2p128_y_0 =38799853089443519372474884917849014410429794312182895329810583938938235910009;

/* edwards representation */

uint256 constant A=0x076d06;//486662, montgomery representation coefficient A
uint256 constant delta=0x2aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaad2451;//(p + A) / 3 mod p
uint256 constant c=0x70d9120b9f5ff9442d84f723fc03b0813a5e2c2eb482e57d3391fb5500ba81e7;// = sqrt(-(A + 2)) mod 255^19
//sqrt of -1
uint256 constant sqrtm1=0x2b8324804fc1df0b2b4d00993dfbd7a72f431806ad2fe478c4ee1b274a0ea0b0;
uint256 constant d_0 = 0x52036cee2b6ffe738cc740797779e89800700a4d4141d8ab75eb4dca135978a3;//edwards form d coefficient

uint256 constant edX = 0x216936D3CD6E53FEC0A4E231FDD6DC5C692CC7609525A7B2C9562D608F25D51A;//base point X
uint256 constant edY = 0x6666666666666666666666666666666666666666666666666666666666666658;//base point Y
//P+3 div 8
uint256 constant pp3div8=0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe;

// src/elliptic/SCL_mulmuladdX_fullgenW.sol
/********************************************************************************************/
/*
#/*   ╔═╗╔╦╗╔═╗╔═╗╔╦╗╦ ╦  ╔═╗╦═╗╦ ╦╔═╗╔╦╗╔═╗╦  ╦╔╗ 
#/*   ╚═╗║║║║ ║║ ║ ║ ╠═╣  ║  ╠╦╝╚╦╝╠═╝ ║ ║ ║║  ║╠╩╗
#/*   ╚═╝╩ ╩╚═╝╚═╝o╩ ╩ ╩  ╚═╝╩╚═ ╩ ╩   ╩ ╚═╝╩═╝╩╚═╝
#/*              
#/* Copyright (C) 2024 - Renaud Dubois - This file is part of SCL (Smoo.th CryptoLib) project
/* License: This software is licensed under MIT License                                        
/* 
/********************************************************************************************/
/* This file implements elliptic curve over short weierstrass form, with coefficient a=-3, with xyzz coordinates */
/* It is a custom 4 dimensional version of Shamir's trick (tis not a window)*/
/* (gen= any curve, sw=short weierstrass) */
/* b4=Four dimensional multiexponentiation */

//Starting from mload(0x40) this is the mapping in allocated memory
//https://medium.com/@ac1d_eth/technical-exploration-of-inline-assembly-in-solidity-b7d2b0b2bda8
//mapping from 0x40 in memory
uint256 constant __Prec_T8=0x800;
uint256 constant __Ap=0x820;
uint256 constant __y2=0x840;
uint256 constant ___zzz2=0x860;//temporary address for zzz2
uint256 constant __free=0x880;

//mapping from Q in input to function, contains Qx, Qy, p, a, gx, gy
//where P' is P multiplied by 2 pow 128 for shamir's multidimensional trick
//todo: remove all magic numbers
uint constant __Qx=0x00;
uint constant __Qy=0x20;
uint constant __modp=0x40;
uint constant __a=0x60;
uint constant __gx=0x80;
uint constant __gy=0xa0;

//this function is for use only after validation of the Q input:
//Q shall belongs to the curve, and different from -P, -P128, -(P+P128), ...
//those 16 values are tested by the ValidateKey function
//due to handling of Neutral element, this function will not work for 16 specific weak keys
//those value are excluded from the 
function ecGenMulmuladdB4W(
        uint256 [6] memory Q,//store Qx, Qy,  p, a, gx, gy, 
        uint256 scalar_u,
        uint256 scalar_v
    )   view returns (uint256 X, uint Y) {
        uint256 mask=1<<255;
        /* I. precomputations phase */
      

        if(scalar_u==0&&scalar_v==0){
            return (0,0);
        }
     
        uint256 ZZZ;
        uint256 ZZ;
     
       // bytes memory Mem = new bytes(16*4*32);
        assembly ("memory-safe") {
        
         mstore(0x40, add(mload(0x40), __Prec_T8))
         mstore(add(mload(0x40), __Ap), mload(add(Q, __modp)))  //load modulus into AP addresse 

          //store 4 256 bits values starting from addr+offset
       
          /* I. precomputations */
          //allocate memory for 15 projective points, first slot is unused
          {
           let _modulusp:=mload(add(mload(0x40), __Ap))   

              function mstore4(addr, offset, val1, val2, val3, val4){
             mstore(add(offset, addr),val1 )
             offset:=add(32, offset)
             mstore(add(offset, addr),val2 )
             offset:=add(32, offset)
             mstore(add(offset, addr),val3 )
             offset:=add(32, offset)
             mstore(add(offset, addr),val4 )
             offset:=add(32, offset)
          }

         function ecDbl(x, y, zz, zzz, _p,a) -> _x, _y, _zz, _zzz{
            let T1 := mulmod(2, y, _p) //U = 2*Y1, y free
                let T2 := mulmod(T1, T1, _p) // V=U^2
                let T3 := mulmod(x, T2, _p) // S = X1*V
                T1 := mulmod(T1, T2, _p) // W=UV
                _y:= addmod(mulmod(3, mulmod(x,x,_p),_p),mulmod(a,mulmod(zz,zz,_p),_p),_p)//M=3*X12+aZZ12  
                
                _zzz := mulmod(T1, zzz, _p) //zzz3=W*zzz1
                _zz := mulmod(T2, zz, _p) //zz3=V*ZZ1
                
                _x := addmod(mulmod(_y, _y, _p), mulmod(sub(_p,2), T3, _p), _p) //X3=M^2-2S
                T2 := mulmod(_y, addmod(_x, sub(_p, T3), _p), _p) //-M(S-X3)=M(X3-S)

                _y := addmod(mulmod(T1, y, _p), T2, _p) //-Y3= W*Y1-M(S-X3), we replace Y by -Y to avoid a sub in ecAdd
                _y:= sub(_p, _y)
         }

         //normalized addition of two point, must not be neutral input 
         function ecAddn2(x1, y1, zz1, zzz1, x2, y2, _p) -> _x, _y, _zz, _zzz {
                y1 := sub(_p, y1)
                y2 := addmod(mulmod(y2, zzz1, _p), y1, _p)
                x2 := addmod(mulmod(x2, zz1, _p), sub(_p, x1), _p)
                _x := mulmod(x2, x2, _p) //PP = P^2
                _y := mulmod(_x, x2, _p) //PPP = P*PP
                _zz := mulmod(zz1, _x, _p) ///ZZ3 = ZZ1*PP
                _zzz := mulmod(zzz1, _y, _p) ///ZZZ3 = ZZZ1*PPP
                zz1 := mulmod(x1, _x, _p) //Q = X1*PP
                _x := addmod(addmod(mulmod(y2, y2, _p), sub(_p, _y), _p), mulmod(sub(_p,2), zz1, _p), _p) //R^2-PPP-2*Q

                x1:=mulmod(addmod(zz1, sub(_p, _x), _p), y2, _p)//necessary split not to explose stack
                _y := addmod(x1, mulmod(y1, _y, _p), _p) //R*(Q-X3)
           }

          mstore4(mload(0x40), 128, mload(add(Q,__gx)), mload(add(Q,__gy)), 1, 1)    //G the base point [1]
          X, Y, ZZ, ZZZ:=ecDbl(mload(add(Q,__gx)), mload(add(Q,__gy)), 1, 1, _modulusp, mload(add(Q,__a)))
          mstore4(mload(0x40), 256, X, Y, ZZ, ZZZ)//2G  [2]
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ, mload(add(Q,__gx)), mload(add(Q,__gy)), _modulusp)//3G
          mstore4(mload(0x40), 384, X, Y, ZZ, ZZZ)//3G  [3]
          mstore4(mload(0x40), 512, mload(add(Q,__Qx)), mload(add(Q,__Qy)), 1, 1)//Q  the public key [4]
          X:=mload(add(Q,__gx))
          Y:= mload(add(Q,__gy))
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y, 1, 1,  mload(add(Q,__Qx)), mload(add(Q,__Qy)),_modulusp)
          mstore4(mload(0x40), 640, X, Y, ZZ, ZZZ)  //G+Q  [5]
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ,  mload(add(Q,__gx)), mload(add(Q,__gy)),_modulusp)
          mstore4(mload(0x40), 768, X, Y, ZZ, ZZZ) //2G+Q  [6]
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ,  mload(add(Q,__gx)), mload(add(Q,__gy)),_modulusp)
          mstore4(mload(0x40), 896, X, Y, ZZ, ZZZ)  //3G+Q  [7]
     
          X:=mload(add(Q,__Qx))
          Y:= mload(add(Q,__Qy))
          X, Y, ZZ, ZZZ:=ecDbl(X,Y, 1, 1, _modulusp, mload(add(Q,__a)))//2Q [8]
          mstore4(mload(0x40), 1024, X, Y, ZZ, ZZZ)  //2Q
        
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ,  mload(add(Q,__gx)), mload(add(Q,__gy)),_modulusp)
          mstore4(mload(0x40), 1152, X, Y, ZZ, ZZZ)  //G+2Q  //[9]
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ,  mload(add(Q,__gx)), mload(add(Q,__gy)),_modulusp)
          mstore4(mload(0x40), 1280, X, Y, ZZ, ZZZ)  //2G+2Q  //[10]
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ,  mload(add(Q,__gx)), mload(add(Q,__gy)),_modulusp)
          mstore4(mload(0x40), 1408, X, Y, ZZ, ZZZ)  //3G+2Q  //[11]
          X:=mload(add(mload(0x40), 1024))//load 2Q 
          Y:=mload(add(mload(0x40), 1056))
          ZZ:=mload(add(mload(0x40), 1088))
          ZZZ:=mload(add(mload(0x40), 1120))
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ,  mload(add(Q,__Qx)), mload(add(Q,__Qy)),_modulusp)//3Q
          mstore4(mload(0x40), 1536, X, Y, ZZ, ZZZ)  //3Q  //[12]
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ,  mload(add(Q,__gx)), mload(add(Q,__gy)),_modulusp)
          mstore4(mload(0x40), 1664, X, Y, ZZ, ZZZ)  //3Q+G  //[13]
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ,  mload(add(Q,__gx)), mload(add(Q,__gy)),_modulusp)
          mstore4(mload(0x40), 1792, X, Y, ZZ, ZZZ)  //3Q+2G  //[14]
          X, Y, ZZ, ZZZ:=ecAddn2(X,Y,ZZ,ZZZ,  mload(add(Q,__gx)), mload(add(Q,__gy)),_modulusp)
          mstore4(mload(0x40), 1920, X, Y, ZZ, ZZZ)  //3Q+3G  //[15]
          }

        /*II. First MSB Window*/
                ZZZ:=0
               
                for {} iszero(ZZZ) { mask := shr(2, mask) }{
                 //ZZZ:=add(add(sub(1,iszero(and(scalar_u, mask))), shl(1,sub(1,iszero(and(shr(1, scalar_u), mask))))),
                 //          add(shl(2,sub(1,iszero(and(scalar_v, mask)))), shl(3,sub(1,iszero(and(shr(1, scalar_v), mask))))))
                  ZZZ:=add(add(
                  sub(1,iszero(and(scalar_u, shr(1,mask)))),//p0
                  shl(1,sub(1,iszero(and(scalar_u, mask))))),//p1
                  add(shl(2,sub(1,iszero(and(scalar_v, shr(1,mask))))),//q0
                  shl(3,sub(1,iszero(and(scalar_v, mask)))))//q1
                  )
                }
              /* Accumulation is equal to first MSB window*/    
              X:=mload(add(mload(0x40),shl(7,ZZZ)))//X
              Y:=mload(add(mload(0x40),add(32, shl(7,ZZZ))))//Y
              ZZ:=mload(add(mload(0x40),add(64, shl(7,ZZZ))))//ZZ
              ZZZ:=mload(add(mload(0x40),add(96, shl(7,ZZZ))))//ZZZ

             let Mem:=mload(0x40)
             let _p:=mload(add(Mem, __Ap))
        /*III. Main loop */
            //(X,Y,ZZ,ZZZ)=ec_Dbl(X,Y,ZZ,ZZZ);
            //TODO, replace mul by shifts
                for {} gt(mask, 0) { mask := shr(2, mask) } {
                   

                {      
                //X,Y,ZZ,ZZZ:=ecDblNeg(X,Y,ZZ,ZZZ), not having it inplace increase by 12K the cost of the function
                
                let T1 := mulmod(2, Y, _p) //U = 2*Y1, y free
                let T2 := mulmod(T1, T1, _p) // V=U^2
                let T3 := mulmod(X, T2, _p) // S = X1*V
                T1 := mulmod(T1, T2, _p) // W=UV
                let T4:=mulmod(mload(add(Q,__a)),mulmod(ZZ,ZZ,_p),_p)//aZZ1^2

                T4 := addmod(mulmod(3, mulmod(X,X,_p),_p),T4,_p)//M=3*X12+aZZ12  
                ZZZ := mulmod(T1, ZZZ, _p) //zzz3=W*zzz1
                ZZ := mulmod(T2, ZZ, _p) //zz3=V*ZZ1

                X:=sub(_p,2)//-2
                X := addmod(mulmod(T4, T4, _p), mulmod(X, T3, _p), _p) //X3=M^2-2S
                T2 := mulmod(T4, addmod(X, sub(_p, T3), _p), _p) //-M(S-X3)=M(X3-S)
                Y := addmod(mulmod(T1, Y, _p), T2, _p) //-Y3= W*Y1-M(S-X3), we replace Y by -Y to avoid a sub in ecAdd
                Y:=sub(_p,Y)
                
                }
                {//inline DblNeg      
                //X,Y,ZZ,ZZZ:=ecDblNeg(X,Y,ZZ,ZZZ), not having it inplace increase by 12K the cost of the function
                
                let T1 := mulmod(2, Y, _p) //U = 2*Y1, y free
                let T2 := mulmod(T1, T1, _p) // V=U^2
                let T3 := mulmod(X, T2, _p) // S = X1*V
                T1 := mulmod(T1, T2, _p) // W=UV
                let T4:=mulmod(mload(add(Q,__a)),mulmod(ZZ,ZZ,_p),_p)//aZZ1^2

                T4 := addmod(mulmod(3, mulmod(X,X,_p),_p),T4,_p)//M=3*X12+aZZ12  
                ZZZ := mulmod(T1, ZZZ, _p) //zzz3=W*zzz1
                ZZ := mulmod(T2, ZZ, _p) //zz3=V*ZZ1
                X:=sub(_p,2)//-2
                X := addmod(mulmod(T4, T4, _p), mulmod(X, T3, _p), _p) //X3=M^2-2S
                T2 := mulmod(T4, addmod(X, sub(_p, T3), _p), _p) //-M(S-X3)=M(X3-S)
                Y := addmod(mulmod(T1, Y, _p), T2, _p) //-Y3= W*Y1-M(S-X3), we replace Y by -Y to avoid a sub in ecAdd
                //Y:=sub(p,Y)
                
                }

             //   let T4:=shl(128,mask)  
             // let T1:=add(add(sub(1,iszero(and(scalar_u, mask))), shl(1,sub(1,iszero(and(scalar_u, T4))))),
              //             add(shl(2,sub(1,iszero(and(scalar_v, mask)))), shl(3,sub(1,iszero(and(T4, scalar_v))))))
               
               let T1:=add(add(
                  sub(1,iszero(and(scalar_u, shr(1,mask)))),//p0
                  shl(1,sub(1,iszero(and(scalar_u, mask))))),//p1
                  add(shl(2,sub(1,iszero(and(scalar_v, shr(1,mask))))),//q0
                  shl(3,sub(1,iszero(and(scalar_v, mask)))))//q1
               )
              if iszero(T1) {
                            Y := sub(_p, Y)
                            continue
              }
              //inlined ec_Add
               T1:=shl(7, T1)//computed value address offset      
               
               let T4:=mload(add(Mem,T1))//X2
               mstore(add(Mem, ___zzz2), mload(add(Mem,add(96,T1))))//ZZZ2
               //accumulation is Neutral, so accumulation becomes Window
              //exception raised by wycheproof/ecdsa_secp256r1_sha256_p1363_test.json EcdsaP1363Verify SHA-256 #58
              if iszero(ZZ) {
                            X := T4//X2
                            Y := mload(add(Mem,add(32,T1)))//Y2
                            ZZ := mload(add(Mem,add(64,T1)))//ZZ2
                            ZZZ := mload(add(Mem,add(96,T1)))//ZZZ2
                            continue
                        }
                
                 mstore(add(Mem,__y2), addmod(mulmod( mload(add(Mem,add(32,T1))), ZZZ, _p), mulmod(Y,mload(add(Mem, ___zzz2)), _p), _p))//R=S2-S1, sub avoided
                 T1:=mload(add(Mem,add(64,T1)))//zz2
                 let T2 := addmod(mulmod(T4, ZZ, _p), sub(_p, mulmod(X,T1,_p)), _p)//P=U2-U1

                        //special case ecAdd(P,P)=EcDbl
                        if iszero(mload(add(Mem,__y2))) {
                            if iszero(T2) {
                                T1 := mulmod(sub(_p,2), Y, _p) //U = 2*Y1, y free
                                T2 := mulmod(T1, T1, _p) // V=U^2
                                mstore(add(Mem,__y2), mulmod(X, T2, _p)) // S = X1*V

                                T1 := mulmod(T1, T2, _p) // W=UV
                                T4:=mulmod(mload(add(Q,__a)),mulmod(ZZ,ZZ,_p),_p)
                                T4 := addmod(mulmod(3, mulmod(X,X,_p),_p),T4,_p)//M=3*X12+aZZ12   //M

                                ZZZ := mulmod(T1, ZZZ, _p) //zzz3=W*zzz1
                                ZZ := mulmod(T2, ZZ, _p) //zz3=V*ZZ1, V free

                                X := addmod(mulmod(T4, T4, _p), mulmod(sub(_p,2), mload(add(Mem, __y2)), _p), _p) //X3=M^2-2S
                                T2 := mulmod(T4, addmod(mload(add(Mem, __y2)), sub(_p, X), _p), _p) //M(S-X3)

                                Y := addmod(T2, mulmod(T1, Y, _p), _p) //Y3= M(S-X3)-W*Y1

                                continue
                            }
                        }
                  T4 := mulmod(T2, T2, _p) //PP
                  T2 := mulmod(T4, T2, _p) //PPP
                  ZZ := mulmod(mulmod(ZZ, T4,_p), T1 ,_p)//zz3=zz1*zz2*PP
                  T1:= mulmod(X,T1, _p)
                  ZZZ := mulmod(mulmod(ZZZ, T2, _p), mload(add(Mem, ___zzz2)),_p) // zzz3=zzz1*zzz2*PPP
                  X := addmod(addmod(mulmod(mload(add(Mem, __y2)), mload(add(Mem, __y2)), _p), sub(_p, T2), _p), mulmod( T1 ,mulmod(sub(_p,2), T4, _p),_p ), _p)// R2-PPP-2*U1*PP
                  T4 := mulmod(T1, T4, _p)//Q=U1*PP
                  Y := addmod(mulmod(addmod(T4, sub(_p, X), _p), mload(add(Mem, __y2)), _p), mulmod(mulmod(Y,mload(add(Mem, ___zzz2)), _p), T2, _p), _p)// R*(Q-X3)-S1*PPP

               }//endloop   
              
                /* IV. Normalization */
                //(X,)=ec_Normalize(X,Y,ZZ,ZZZ);
                
                mstore(0x40, __free)
                 let T := mload(0x40)
                mstore(add(T, 0x60), ZZZ)
                //(X,Y)=ecZZ_SetAff(X,Y,zz, zzz);
                //T[0] = inverseModp_Hard(T[0], p); //1/zzz, inline modular inversion using Memmpile:
                // Define length of base, exponent and modulus. 0x20 == 32 bytes
                mstore(T, 0x20)
                mstore(add(T, 0x20), 0x20)
                mstore(add(T, 0x40), 0x20)
                // Define variables base, exponent and modulus
                //mstore(add(pointer, 0x60), u)
                mstore(add(T, 0x80), sub(_p,2))
                mstore(add(T, 0xa0), _p)

                // Call the precompiled contract 0x05 = ModExp
                if iszero(staticcall(not(0), 0x05, T, 0xc0, T, 0x20)) {
                    mstore(0x40, _ModExpError)
                    revert(0x40, 0x20)  }
                    
                Y := mulmod(Y, mload(T), _p)//Y/ZZZ
                ZZ :=mulmod(ZZ, mload(T),_p) //1/z
                ZZ:= mulmod(ZZ,ZZ,_p) //1/zz
                X := mulmod(X, ZZ, _p) //X/zz   
          }//end assembly
    }
    

// src/fields/SCL_secp256r1.sol
/********************************************************************************************/
/*
/*     ___                _   _       ___               _         _    _ _    
/*    / __|_ __  ___  ___| |_| |_    / __|_ _ _  _ _ __| |_ ___  | |  (_) |__ 
/*    \__ \ '  \/ _ \/ _ \  _| ' \  | (__| '_| || | '_ \  _/ _ \ | |__| | '_ \
/*   |___/_|_|_\___/\___/\__|_||_|  \___|_|  \_, | .__/\__\___/ |____|_|_.__/
/*                                         |__/|_|           
/*              
/* Copyright (C) 2023 - Renaud Dubois - This file is part of SCL (Smooth CryptoLib) project
/* License: This software is licensed under MIT License                                        
/********************************************************************************************/

// prime field modulus of the secp256r1 curve
uint256 constant p_1 = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF;
// short weierstrass first coefficient
uint256 constant a_1 = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFC;
// short weierstrass second coefficient
uint256 constant b_1 = 0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B;
// the affine coordinates of the generating point on the curve
//48439561293906451759052585252797914202762949526041747995844080717082404635286
uint256 constant gx_1 = 0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296;
//36134250956749795798585127919587881956611106672985015071877198253568414405109
uint256 constant gy_1 = 0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5;
// the order of the curve, i.e., the number of points on the curve
uint256 constant n_1 = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551;

/*//////////////////////////////////////////
                            CONSTANTS
//////////////////////////////////////////*/

// -2 mod(p), used to accelerate inversion and doubling operations by avoiding negation
uint256 constant pMINUS_2_1 = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFD;
// -2 mod(n), used to speed up inversion operations
uint256 constant nMINUS_2_1 = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC63254F;

//precomputed 2^128.G
//0x447d739beedb5e67fb982fd588c6766efc35ff7dc297eac357c84fc9d789bd85
uint256 constant gpow2p128_x_1 = 30978927491535595270285342502287618780579786685182435011955893029189825707397;
uint256 constant gpow2p128_y_1= 20481551163499472379222416201371726725754635744576161296521936142531318405938;
uint256 constant _HIBIT_CURVE_1=255;
uint256 constant FIELD_OID=_SECP256R1;
 //P+1 div 4, used for sqrtmod computation
 uint256 constant pp1div4=0x3fffffffc0000000400000000000000000000000400000000000000000000000;

uint256 constant   _MODEXP_PRECOMPILE=0x05;
// the representation of -1 over 256 bits
uint256 constant MINUS_1 = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint256 constant d_1=  _UNUSED;
uint256 constant deux_d = _UNUSED;
uint256 constant unscaling_factor= _UNUSED;
uint256 constant scaling_factor= _UNUSED;

uint256 constant _2gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _2gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _3gx=42877656971275811310262564894490210024759287182177196162425349131675946712428;
uint256 constant _3gy=61154801112014214504178281461992570017247172004704277041681093927569603776562;
uint256 constant _4gx=102369864249653057322725350723741461599905180004905897298779971437827381725266;
uint256 constant _4gy=101744491111635190512325668403432589740384530506764148840112137220732283181254;

uint256 constant _5gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _5gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _6gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _6gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _7gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _7gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _8gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _8gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _9gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _9gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _10gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _10gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _11gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _11gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _12gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _12gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _13gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _13gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _14gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _14gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;
uint256 constant _15gx=56515219790691171413109057904011688695424810155802929973526481321309856242040;
uint256 constant _15gy=3377031843712258259223711451491452598088675519751548567112458094635497583569;

/*_G_POINT*2
(56515219790691171413109057904011688695424810155802929973526481321309856242040 : 3377031843712258259223711451491452598088675519751548567112458094635497583569 : 1)
sage: _G_POINT*3
(42877656971275811310262564894490210024759287182177196162425349131675946712428 : 61154801112014214504178281461992570017247172004704277041681093927569603776562 : 1)
sage: _G_POINT*4
(102369864249653057322725350723741461599905180004905897298779971437827381725266 : 101744491111635190512325668403432589740384530506764148840112137220732283181254 : 1)
sage: _G_POINT*5
(36794669340896883012101473439538929759152396476648692591795318194054580155373 : 101659946828913883886577915207667153874746613498030835602133042203824767462820 : 1)
sage: _G_POINT*6
(79653159259317329199152975905021693207262715618295428672027927511489832980905 : 105099244361861367422779349381909628134794498213392835359532911141293690159074 : 1)
sage: _G_POINT*7
(64375483017717711348634889601793836329966447963510648681625681211348943876771 : 52431391916983504423217627849020916729601969409053901192561322805962577543348 : 1)
sage: _G_POINT*8
(44710890534849379681007195543719586089737754824560621976448707498688874787731 : 78410552107786285403689301656392479612049391334024095564584156230482213311870 : 1)
sage: _G_POINT*9
(106026447472237217594103756757091873528548576106367144586170196380839010672352 : 19066521425813101412078385704618669688199787690556935461623958781864528857338 : 1)
sage: _G_POINT*10
(93611846365601674425599200647886473617443872040541410036779615417472400060991 : 61299672808462629900136024686264045542397545919962042795596947287593974695795 : 1)
sage: _G_POINT*11
(28412803729898893058558238221310261427084375743576167377786533380249859400145 : 65403602826180996396520286939226973026599920614829401631985882360676038096704 : 1)
sage: _G_POINT*12
(52521004185641536627266600536804816931535329133355539962020980193802383057860 : 3365321999886721389269937144276711091585627196865605815969312301872807444947 : 1)
sage: _G_POINT*13
(10623191994993397449217730442198332685419647040822028787120372345201232391169 : 45109985299617300571846506882481132822837374452436097494820998411881657384920 : 1)
sage: _G_POINT*14
(38403262968984431726992065809397801166868659563255596809893498026441953153547 : 111088643870609220449345638248812642769306967281233677460251511569904126964597 : 1)
sage: _G_POINT*15
(108677532895904936863904823330600106055145041255062888673713681538132314135903 : 82195926338128401624329850334826772981689991100719104119047727086732126146358 : 1)

*/

// external/sha512/Sha2Ext.sol

library Sha2Ext {
    function sha2(bytes memory message, uint64[8] memory h) internal pure {
        uint64[80] memory k = [
            0x428a2f98d728ae22,
            0x7137449123ef65cd,
            0xb5c0fbcfec4d3b2f,
            0xe9b5dba58189dbbc,
            0x3956c25bf348b538,
            0x59f111f1b605d019,
            0x923f82a4af194f9b,
            0xab1c5ed5da6d8118,
            0xd807aa98a3030242,
            0x12835b0145706fbe,
            0x243185be4ee4b28c,
            0x550c7dc3d5ffb4e2,
            0x72be5d74f27b896f,
            0x80deb1fe3b1696b1,
            0x9bdc06a725c71235,
            0xc19bf174cf692694,
            0xe49b69c19ef14ad2,
            0xefbe4786384f25e3,
            0x0fc19dc68b8cd5b5,
            0x240ca1cc77ac9c65,
            0x2de92c6f592b0275,
            0x4a7484aa6ea6e483,
            0x5cb0a9dcbd41fbd4,
            0x76f988da831153b5,
            0x983e5152ee66dfab,
            0xa831c66d2db43210,
            0xb00327c898fb213f,
            0xbf597fc7beef0ee4,
            0xc6e00bf33da88fc2,
            0xd5a79147930aa725,
            0x06ca6351e003826f,
            0x142929670a0e6e70,
            0x27b70a8546d22ffc,
            0x2e1b21385c26c926,
            0x4d2c6dfc5ac42aed,
            0x53380d139d95b3df,
            0x650a73548baf63de,
            0x766a0abb3c77b2a8,
            0x81c2c92e47edaee6,
            0x92722c851482353b,
            0xa2bfe8a14cf10364,
            0xa81a664bbc423001,
            0xc24b8b70d0f89791,
            0xc76c51a30654be30,
            0xd192e819d6ef5218,
            0xd69906245565a910,
            0xf40e35855771202a,
            0x106aa07032bbd1b8,
            0x19a4c116b8d2d0c8,
            0x1e376c085141ab53,
            0x2748774cdf8eeb99,
            0x34b0bcb5e19b48a8,
            0x391c0cb3c5c95a63,
            0x4ed8aa4ae3418acb,
            0x5b9cca4f7763e373,
            0x682e6ff3d6b2b8a3,
            0x748f82ee5defb2fc,
            0x78a5636f43172f60,
            0x84c87814a1f0ab72,
            0x8cc702081a6439ec,
            0x90befffa23631e28,
            0xa4506cebde82bde9,
            0xbef9a3f7b2c67915,
            0xc67178f2e372532b,
            0xca273eceea26619c,
            0xd186b8c721c0c207,
            0xeada7dd6cde0eb1e,
            0xf57d4f7fee6ed178,
            0x06f067aa72176fba,
            0x0a637dc5a2c898a6,
            0x113f9804bef90dae,
            0x1b710b35131c471b,
            0x28db77f523047d84,
            0x32caab7b40c72493,
            0x3c9ebe0a15c9bebc,
            0x431d67c49c100d4c,
            0x4cc5d4becb3e42b6,
            0x597f299cfc657e2a,
            0x5fcb6fab3ad6faec,
            0x6c44198c4a475817
        ];

        bytes memory padding = padMessage(message);
        require(padding.length % 128 == 0, "PADDING_ERROR");
        uint64[80] memory w;
        uint64[8] memory temp;
        uint64[16] memory blocks;
        uint256 messageLength = (message.length / 128) * 128;
        unchecked {
            for (uint256 i = 0; i < (messageLength + padding.length); i += 128) {
                if (i < messageLength) {
                    getBlock(message, blocks, i);
                } else {
                    getBlock(padding, blocks, i - messageLength);
                }
                for (uint256 j = 0; j < 16; ++j) {
                    w[j] = blocks[j];
                }
                for (uint256 j = 16; j < 80; ++j) {
                    w[j] = gamma1(w[j - 2]) + w[j - 7] + gamma0(w[j - 15]) + w[j - 16];
                }
                for (uint256 j = 0; j < 8; ++j) {
                    temp[j] = h[j];
                }
                for (uint256 j = 0; j < 80; ++j) {
                    uint64 t1 = temp[7] + sigma1(temp[4]) + ch(temp[4], temp[5], temp[6]) + k[j] + w[j];
                    uint64 t2 = sigma0(temp[0]) + maj(temp[0], temp[1], temp[2]);
                    temp[7] = temp[6];
                    temp[6] = temp[5];
                    temp[5] = temp[4];
                    temp[4] = temp[3] + t1;
                    temp[3] = temp[2];
                    temp[2] = temp[1];
                    temp[1] = temp[0];
                    temp[0] = t1 + t2;
                }
                for (uint256 j = 0; j < 8; ++j) {
                    h[j] += temp[j];
                }
            }
        }
    }

    function sha384(bytes memory message) internal pure returns (bytes32, bytes16) {
        uint64[8] memory h = [
            0xcbbb9d5dc1059ed8,
            0x629a292a367cd507,
            0x9159015a3070dd17,
            0x152fecd8f70e5939,
            0x67332667ffc00b31,
            0x8eb44a8768581511,
            0xdb0c2e0d64f98fa7,
            0x47b5481dbefa4fa4
        ];
        sha2(message, h);
        return (
            bytes32(abi.encodePacked(bytes8(h[0]), bytes8(h[1]), bytes8(h[2]), bytes8(h[3]))),
            bytes16(abi.encodePacked(bytes8(h[4]), bytes8(h[5])))
        );
    }

    function sha512(bytes memory message) internal pure returns (bytes32, bytes32) {
        uint64[8] memory h = [
            0x6a09e667f3bcc908,
            0xbb67ae8584caa73b,
            0x3c6ef372fe94f82b,
            0xa54ff53a5f1d36f1,
            0x510e527fade682d1,
            0x9b05688c2b3e6c1f,
            0x1f83d9abfb41bd6b,
            0x5be0cd19137e2179
        ];
        sha2(message, h);
        return (
            bytes32(abi.encodePacked(bytes8(h[0]), bytes8(h[1]), bytes8(h[2]), bytes8(h[3]))),
            bytes32(abi.encodePacked(bytes8(h[4]), bytes8(h[5]), bytes8(h[6]), bytes8(h[7])))
        );
    }

    function padMessage(bytes memory message) internal pure returns (bytes memory) {
        uint256 messageLength = message.length;
        bytes8 bitLength = bytes8(uint64(messageLength * 8));
        uint256 mdi = messageLength % 128;
        uint256 paddingLength;
        if (mdi < 112) {
            paddingLength = 119 - mdi;
        } else {
            paddingLength = 247 - mdi;
        }
        bytes memory padding = new bytes(paddingLength);
        bytes memory tail = LibBytes.slice(message, messageLength - mdi, messageLength);
        return abi.encodePacked(tail, bytes1(0x80), padding, bitLength);
    }

    function getBlock(bytes memory message, uint64[16] memory blocks, uint256 index) internal pure {
        for (uint256 i = 0; i < 16; ++i) {
            blocks[i] = uint64(LibBytes.readBytes8(message, index + i * 8));
        }
    }

    function ch(uint64 x, uint64 y, uint64 z) internal pure returns (uint64) {
        return (x & y) ^ (~x & z);
    }

    function maj(uint64 x, uint64 y, uint64 z) internal pure returns (uint64) {
        return (x & y) ^ (x & z) ^ (y & z);
    }

    function sigma0(uint64 x) internal pure returns (uint64) {
        return (rotateRight(x, 28) ^ rotateRight(x, 34) ^ rotateRight(x, 39));
    }

    function sigma1(uint64 x) internal pure returns (uint64) {
        return (rotateRight(x, 14) ^ rotateRight(x, 18) ^ rotateRight(x, 41));
    }

    function gamma0(uint64 x) internal pure returns (uint64) {
        return (rotateRight(x, 1) ^ rotateRight(x, 8) ^ (x >> 7));
    }

    function gamma1(uint64 x) internal pure returns (uint64) {
        return (rotateRight(x, 19) ^ rotateRight(x, 61) ^ (x >> 6));
    }

    function rotateRight(uint64 x, uint64 n) internal pure returns (uint64) {
        return (x << (64 - n)) | (x >> n);
    }
}

// src/include/SCL_field.h.sol
//********************************************************************************************/
//*
//*     ___                _   _       ___               _         _    _ _    
//*    / __|_ __  ___  ___| |_| |_    / __|_ _ _  _ _ __| |_ ___  | |  (_) |__ 
//*    \__ \ '  \/ _ \/ _ \  _| ' \  | (__| '_| || | '_ \  _/ _ \ | |__| | '_ \
//*   |___/_|_|_\___/\___/\__|_||_|  \___|_|  \_, | .__/\__\___/ |____|_|_.__/
//*                                         |__/|_|           
//*              
//* Copyright (C) 2023 - Renaud Dubois - This file is part of SCL (Smooth CryptoLib) project
//* License: This software is licensed under MIT License                                        
//********************************************************************************************/

//choose the field to import

//import { p, gx, gy, gpow2p128_x, gpow2p128_y, n, pMINUS_2, nMINUS_2, MINUS_1, _HIBIT_CURVE, FIELD_OID } from "@solidity/fields/SCL_ed25519.sol";
//import { deux_d, p, pp1div4, a,b,gx, gy, gpow2p128_x, gpow2p128_y, n, pMINUS_2, nMINUS_2, MINUS_1, _HIBIT_CURVE, _MODEXP_PRECOMPILE, FIELD_OID } from "@solidity/fields/SCL_ecstark.sol";

//import {unscaling_factor, d, scaling_factor, FIELD_OID,  MINUS_1, p,n, gx, gy, pMINUS_2, nMINUS_2, deux_d,a, _HIBIT_CURVE,b , gpow2p128_x, gpow2p128_y, _MODEXP_PRECOMPILE , pp1div4 } from "@solidity/fields/SCL_babyjujub.sol";

// src/hash/SCL_sha512.sol
/********************************************************************************************/
/*
/*     ___                _   _       ___               _         _    _ _    
/*    / __|_ __  ___  ___| |_| |_    / __|_ _ _  _ _ __| |_ ___  | |  (_) |__ 
/*    \__ \ '  \/ _ \/ _ \  _| ' \  | (__| '_| || | '_ \  _/ _ \ | |__| | '_ \
/*   |___/_|_|_\___/\___/\__|_||_|  \___|_|  \_, | .__/\__\___/ |____|_|_.__/
/*                                         |__/|_|           
/*              
/* Copyright (C) 2023 - Renaud Dubois - This file is part of SCL (Smooth CryptoLib) project
/* License: This software is licensed under MIT License                                        
/* 
/********************************************************************************************/

//https://emn178.github.io/online-tools/sha512.html

library SCL_sha512 {
 
    function Swap512(uint256[2] memory w) internal pure returns(uint256[2] memory r)
    {
        r[0]=Swap256(w[1]);
        r[1]=Swap256(w[0]);

        return r;
    }

    function Swap256(uint256 w) internal pure returns (uint256 x)
    {
        return uint256(Swap128(uint128(w>>128)))^(uint256(Swap128(uint128(w&0xffffffffffffffffffffffffffffffff)))<<128);
    }

    function Swap128(uint128 w) internal pure returns (uint128 x)
    {
        return uint128(Swap64(uint64(w>>64)))^(uint128(Swap64(uint64(w&0xffffffffffffffff)))<<64);
    }

    function Swap64(uint64 w) internal pure returns (uint64 x){
     uint64 tmp= (w >> 32) | (w << 32);
	 tmp = ((tmp & 0xff00ff00ff00ff00) >> 8) |    ((tmp & 0x00ff00ff00ff00ff) << 8); 
	 x = ((tmp & 0xffff0000ffff0000) >> 16) |   ((tmp & 0x0000ffff0000ffff) << 16); 
    }

}

// src/modular/SCL_sqrtMod_5mod8.sol
/********************************************************************************************/
/*
/*   ╔═╗╔╦╗╔═╗╔═╗╔╦╗╦ ╦  ╔═╗╦═╗╦ ╦╔═╗╔╦╗╔═╗╦  ╦╔╗ 
/*   ╚═╗║║║║ ║║ ║ ║ ╠═╣  ║  ╠╦╝╚╦╝╠═╝ ║ ║ ║║  ║╠╩╗
/*   ╚═╝╩ ╩╚═╝╚═╝o╩ ╩ ╩  ╚═╝╩╚═ ╩ ╩   ╩ ╚═╝╩═╝╩╚═╝
/*              
/* Copyright (C) 2024 - Renaud Dubois - This file is part of SCL (Smoo.th CryptoLib) project
/* License: This software is licensed under MIT License (and allways will)   
/* Description: This file implements modular square root computation for modulus p=5 mod 8 (ed25519).                       
/********************************************************************************************/

// @notice Calculate one modular square root of the self given integer . Assume that p=5 mod 8.
// @dev Uses the ModExp precompiled contract at address 0x05 for fast computation using little Fermat theorem
// @param self The integer of which to find the modular inverse
// @return result The modular inverse of the input integer. If the modular inverse doesn't exist, it revert the tx
function SqrtMod(uint256 self) returns (uint256 result){

 assembly ("memory-safe") {
        // load the free memory pointer value
        let pointer := mload(0x40)

        // Define length of base (Bsize)
        mstore(pointer, 0x20)
        // Define the exponent size (Esize)
        mstore(add(pointer, 0x20), 0x20)
        // Define the modulus size (Msize)
        mstore(add(pointer, 0x40), 0x20)
        // Define variables base (B)
        mstore(add(pointer, 0x60), self)
        // Define the exponent (E)
        mstore(add(pointer, 0x80), pp3div8)
        // We save the point of the last argument, it will be override by the result
        // of the precompile call in order to avoid paying for the memory expansion properly
        let _result := add(pointer, 0xa0)
        // Define the modulus (M)
        mstore(_result, p_0)

        // Call the precompiled ModExp (0x05) https://www.evm.codes/precompiled#0x05
        if iszero(
            call(
                not(0), // amount of gas to send
                MODEXP_PRECOMPILE, // target
                0x00, // value in wei
                pointer, // argsOffset
                0xc0, // argsSize (6 * 32 bytes)
                _result, // retOffset (we override M to avoid paying for the memory expansion)
                0x20 // retSize (32 bytes)
            )
        ) { 
           mstore(0x40, _ModExpError)
           revert(0x40, 0x20)
                     }

  result := mload(_result)
//  result :=addmod(result,0,p)
 }
   if(mulmod(result,result,p_0)!=self){
     result=mulmod(result, sqrtm1, p_0);
   }
   if(mulmod(result,result,p_0)!=self){
    assembly{ 
       mstore(0x40, _NotQuadraticResidueError)
       revert(0x40, 0x20)
       }
   }
   return result;
}

// src/modular/SCL_modular.sol
//********************************************************************************************/
//*
//*     ___                _   _       ___               _         _    _ _    
//*    / __|_ __  ___  ___| |_| |_    / __|_ _ _  _ _ __| |_ ___  | |  (_) |__ 
//*    \__ \ '  \/ _ \/ _ \  _| ' \  | (__| '_| || | '_ \  _/ _ \ | |__| | '_ \
//*   |___/_|_|_\___/\___/\__|_||_|  \___|_|  \_, | .__/\__\___/ |____|_|_.__/
//*                                         |__/|_|           
//*              
//* Copyright (C) 2022 - Renaud Dubois - This file is part of SCL (Smooth CryptoLib) project
//* License: This software is licensed under MIT License                                        
//********************************************************************************************/

    /**
     * /* @dev inversion of u mod m using little Fermat theorem via a^(n-2), use of precompiled
     */
    function ModInv(uint256 u, uint256 m) view returns (uint256 result) {

        uint256 mMINUS_2=m-2;

        assembly {
            let pointer := mload(0x40)
            // Define length of base, exponent and modulus. 0x20 == 32 bytes
            mstore(pointer, 0x20)
            mstore(add(pointer, 0x20), 0x20)
            mstore(add(pointer, 0x40), 0x20)
            // Define variables base, exponent and modulus
            mstore(add(pointer, 0x60), u)
            mstore(add(pointer, 0x80), mMINUS_2)
            mstore(add(pointer, 0xa0), m)

            // Call the precompiled contract 0x05 = ModExp
            if iszero(staticcall(not(0), MODEXP_PRECOMPILE, pointer, 0xc0, pointer, 0x20)) {
                  mstore(0x40, _ModInvError)
                  revert(0x40, 0x20) }
            result := mload(pointer)
        }
    }

    /**
     * /* @dev inversion mod nusing little Fermat theorem via a^(n-2), use of precompiled
     */
    function nModInv(uint256 u) view returns (uint256 result) {
        assembly {
            let pointer := mload(0x40)
            // Define length of base, exponent and modulus. 0x20 == 32 bytes
            mstore(pointer, 0x20)
            mstore(add(pointer, 0x20), 0x20)
            mstore(add(pointer, 0x40), 0x20)
            // Define variables base, exponent and modulus
            mstore(add(pointer, 0x60), u)
            mstore(add(pointer, 0x80), nMINUS_2_1)
            mstore(add(pointer, 0xa0), n_1)

            // Call the precompiled contract 0x05 = ModExp
            if iszero(staticcall(not(0), MODEXP_PRECOMPILE, pointer, 0xc0, pointer, 0x20)) {  
                mstore(0x40, _ModInvError)
                revert(0x40, 0x20) } 
            result := mload(pointer)
        }
    }
    
    
    
    

// src/lib/libSCL_EIP6565.sol
/********************************************************************************************/
/*
/*   ╔═╗╔╦╗╔═╗╔═╗╔╦╗╦ ╦  ╔═╗╦═╗╦ ╦╔═╗╔╦╗╔═╗╦  ╦╔╗ 
/*   ╚═╗║║║║ ║║ ║ ║ ╠═╣  ║  ╠╦╝╚╦╝╠═╝ ║ ║ ║║  ║╠╩╗
/*   ╚═╝╩ ╩╚═╝╚═╝o╩ ╩ ╩  ╚═╝╩╚═ ╩ ╩   ╩ ╚═╝╩═╝╩╚═╝
/*              
/* Copyright (C) 2024 - Renaud Dubois - This file is part of SCL (Smoo.th CryptoLib) project
/* License: This software is licensed under MIT License (and allways will)      
/* Description: This file implements the ecdsa verification protocol using Shamir's trick + 4bit windowing.                                        
/********************************************************************************************/

//As specified by Rene Struik in
//https://datatracker.ietf.org/doc/draft-ietf-lwig-curve-representations/

//import modular inversion over prime field defined over curve subgroup of prime order
 
//import point on curve checking

//import point double multiplication and accumulation (RIP7696)

library SCL_EIP6565{

 function ecPow128(uint256 X, uint256 Y, uint256 ZZ, uint256 ZZZ) public view returns(uint256 x128, uint256 y128){
   assembly{
   function vecDbl(x, y, zz, zzz) -> _x, _y, _zz, _zzz{
            let T1 := mulmod(2, y, p_0) //U = 2*Y1, y free
                let T2 := mulmod(T1, T1, p_0) // V=U^2
                let T3 := mulmod(x, T2, p_0) // S = X1*V
                T1 := mulmod(T1, T2, p_0) // W=UV
                let T4 := addmod(mulmod(3, mulmod(x,x,p_0),p_0),mulmod(a_0,mulmod(zz,zz,p_0),p_0),p_0)//M=3*X12+aZZ12  
                _zzz := mulmod(T1, zzz, p_0) //zzz3=W*zzz1
                _zz := mulmod(T2, zz, p_0) //zz3=V*ZZ1

                _x := addmod(mulmod(T4, T4, p_0), mulmod(pMINUS_2_0, T3, p_0), p_0) //X3=M^2-2S
                T2 := mulmod(T4, addmod(_x, sub(p_0, T3), p_0), p_0) //-M(S-X3)=M(X3-S)
                _y := addmod(mulmod(T1, y, p_0), T2, p_0) //-Y3= W*Y1-M(S-X3), we replace Y by -Y to avoid a sub in ecAdd
                _y:= sub(p_0, _y)
         }
         for {x128:=0} lt(x128, 128) { x128:=add(x128,1) }{
           X, Y, ZZ, ZZZ := vecDbl(X, Y, ZZ, ZZZ)
         }
         }
      ZZ=ModInv(ZZ, p_0);
      ZZZ=ModInv(ZZZ,p_0);
      x128=mulmod(X, ZZ, p_0);
      y128=mulmod(Y, ZZZ, p_0);
}
 

    function Swap64(uint64 w) internal pure returns (uint64 x){
     uint64 tmp= (w >> 32) | (w << 32);
	 tmp = ((tmp & 0xff00ff00ff00ff00) >> 8) |    ((tmp & 0x00ff00ff00ff00ff) << 8); 
	 x = ((tmp & 0xffff0000ffff0000) >> 16) |   ((tmp & 0x0000ffff0000ffff) << 16); 
    }

function Edwards2WeierStrass(uint256 x,uint256 y)  internal view returns (uint256 X, uint256 Y){
  //wx = ((1 + ey) * (1 - ey)^-1) + delta
  X=addmod(delta, mulmod(addmod(1,y,p_0),ModInv(addmod(1, p_0-y,p_0),p_0),p_0) ,p_0);
  //  wy = (c * (1 + ey)) * ((1 - ey) * ex)^-1
  
  Y=mulmod(mulmod(c, addmod(1, y, p_0),p_0),        ModInv(mulmod(addmod(1, p_0-y,p_0), x,p_0),p_0),p_0);
}

// ex  = (c * pa) * (3 * my)^-1 (mod p)

function WeierStrass2Edwards(uint256 X,uint256 Y)  internal view returns (uint256 x, uint256 y){
     // pa  = 3 * wx - A
     // ex  = (c * pa) * (3 * wy)^-1 (mod p)
    //  ey = (pa - 3) * (pa + 3)^-1 (mod p)
    uint pa=addmod(mulmod(3,X, p_0), p_0-A,p_0);
    uint inv=ModInv(mulmod(3,Y,p_0),p_0);
    x=mulmod(mulmod(c,pa,p_0), inv,p_0);
    inv=ModInv(addmod(pa,3,p_0),p_0);
  
  //  ey = (pa - 3) * (pa + 3)^-1 (mod p)
    y=mulmod(addmod(pa, p_0-3, p_0), inv, p_0);

}

 function BasePointMultiply(uint256 scalar) public view returns (uint256 x, uint256 y) {
    uint256[6] memory Q=[gpow2p128_x_0,gpow2p128_y_0,p_0,a_0,gx_0,gy_0];
 
    //abusing RIP7696 first opcode for base point multiplication
    (x,y)=ecGenMulmuladdB4W(Q, scalar, 0);
 }

 //todo: speedup by splitting scalars
 function BasePointMultiply_Edwards(uint256 scalar) public view returns (uint256 x, uint256 y) {
   // uint256[6] memory Q=[gpow2p128_x,gpow2p128_y,p,a,gx,gy];
  uint256[6] memory Q=[gx_0,gy_0,p_0,a_0,gpow2p128_x_0,gpow2p128_y_0];
 
    //abusing RIP7696 first opcode for base point multiplication
    (x,y)=ecGenMulmuladdB4W(Q, 0, scalar);
    return WeierStrass2Edwards(x,y);

 }

function SHA512_modq(bytes memory m) internal pure returns (uint256 h)
{
 bytes32 high;
 bytes32 low;
 (high, low)=Sha2Ext.sha512(m);
 uint256[2] memory S=[uint256(high), uint256(low)];
 h= Red512Modq(SCL_sha512.Swap512(S)); //swap then reduce mod q

 return h;
}

/* reduce a 512 bit number modulo curve order, val being interpreted as the number val[0]<<256+val*/
function Red512Modq(uint256[2] memory val) internal pure returns (uint256 h)
{

  return addmod(mulmod(val[0],_2pow256modn, n_0),val[1],n_0);

}

 //eddsa benefit from the 255 bits to compress the parity of y in msb bit
 function edCompress(uint256[2] memory Kpub) internal pure returns(uint256 KPubC){
  KPubC=Kpub[1] +((Kpub[0]&1)<<255) ;

  return KPubC;
 }
 
 

//compute h(r,a,m)
 function  HashInternal(uint256 r, uint256 KpubC, string memory m) internal pure returns (uint256 k)
 {
  /*
  bytes32 high;
  bytes32 low;
  (high, low)=Sha2Ext.sha512(abi.encodePacked(r,KpubC, m));
  uint256[2] memory S=[uint256(high), uint256(low)];
  k= Red512Modq(SCL_sha512.Swap512(S)); //swap then reduce mod q
  */
  return  SHA512_modq(abi.encodePacked(r,KpubC, m));
 }

 //input are expressed msb first, as any healthy mind should.
 function Verify(string memory m, uint256 r, uint256 s, uint256[5] memory extKpub) 
 internal view returns(bool flag){
    uint256 [2] memory S;
   uint256 KpubC=extKpub[4];
   
    // check the value ranges of signature
    if ( s == 0 || s >= n_0) {
            return false;
    }

   r=SCL_sha512.Swap256(r);

   uint256 k=HashInternal(r, KpubC, m);

   uint256[6] memory Q=[extKpub[0], extKpub[1],p_0,a_0,gx_0,gy_0];
 
   
   //uint256 [10] memory Q=[extKpub[0], extKpub[1],extKpub[2], extKpub[3], p, a, gx, gy, gpow2p128_x, gpow2p128_y ];
  (S[0], S[1])=ecGenMulmuladdB4W(Q, s, n_0-k);
  (S[0], S[1])=WeierStrass2Edwards(S[0], S[1]);//back to edwards form
   uint256 recomputed_r=edCompress(S);

   //3.  Check the group equation [8][S]B = [8]R + [8][k]A'.  It's sufficient, 
   //but not required, to instead check [S]B = R + [k]A'.
   //SCL tweak equality to substraction to check [S]B - [k]A' = [S]B + [n-k]A' = R 
   
  
   recomputed_r=SCL_sha512.Swap256(recomputed_r);
   flag=(recomputed_r==r);    

 }

 //input are expressed lsb, require one extra swap compared to msb representation
 function Verify_LE(string memory m, uint256 r, uint256 s, uint256[5] memory extKpub) 
 internal view returns(bool flag){
    uint256 [2] memory S;
   uint256 KpubC=extKpub[4];
   
   s=SCL_sha512.Swap256(s);

   // check the value ranges of signature
    if ( s == 0 || s >= n_0) {
            return false;
    }

   uint256 k=HashInternal(r, KpubC, m);

   uint256[6] memory Q=[extKpub[0], extKpub[1],p_0,a_0,gx_0,gy_0];
 
   
   //uint256 [10] memory Q=[extKpub[0], extKpub[1],extKpub[2], extKpub[3], p, a, gx, gy, gpow2p128_x, gpow2p128_y ];
  (S[0], S[1])=ecGenMulmuladdB4W(Q, s, n_0-k);
  (S[0], S[1])=WeierStrass2Edwards(S[0], S[1]);//back to edwards form
   uint256 recomputed_r=edCompress(S);

   //3.  Check the group equation [8][S]B = [8]R + [8][k]A'.  It's sufficient, 
   //but not required, to instead check [S]B = R + [k]A'.
   //SCL tweak equality to substraction to check [S]B - [k]A' = [S]B + [n-k]A' = R 
   
   recomputed_r=SCL_sha512.Swap256(recomputed_r);
   flag=(recomputed_r==r);    

 }

 function verifyLEWithPubkey(string memory m, uint256 r, uint256 s, bytes32 pubkey, uint256 qx, uint256 qy)
 external view returns(bool flag){
   uint256[5] memory extKpub;
   extKpub[0] = qx;
   extKpub[1] = qy;
   extKpub[4] = uint256(pubkey);
   return Verify_LE(m, r, s, extKpub);
 }
 

}

